# KnativeServing Custom Resource for Air-Gapped Environments
#
# Before applying, replace <PRIVATE_REGISTRY> with your private registry URL.
# Example: default-route-openshift-image-registry.apps.example.com
#
# Usage:
#   1. Edit this file and replace all occurrences of <PRIVATE_REGISTRY>
#   2. kubectl apply -f knative-serving.yaml

apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # Override container registry for air-gapped environment
  registry:
    # Image pull secrets for private registry authentication
    imagePullSecrets:
      - name: knative-registry-creds
    # Default uses ${NAME} placeholder for component name
    # Replace <PRIVATE_REGISTRY> with your registry URL
    default: <PRIVATE_REGISTRY>/knative/${NAME}:v1.18.0
    override:
      # Queue proxy (injected into user workloads)
      queue-proxy: <PRIVATE_REGISTRY>/knative/queue:v1.18.0
      # Kourier ingress components (use container names as keys)
      net-kourier-controller/controller: <PRIVATE_REGISTRY>/knative/kourier:v1.18.0
      kourier-gateway: <PRIVATE_REGISTRY>/envoyproxy/envoy:v1.34-latest
      # Post-install job images
      cleanup: <PRIVATE_REGISTRY>/knative/cleanup:v1.18.0
      migrate: <PRIVATE_REGISTRY>/knative/migrate:v1.18.0

  config:
    config-autoscaler:
      enable-scale-to-zero: "true"
    config-features:
      kubernetes.podspec-affinity: enabled
      kubernetes.podspec-init-containers: enabled
      kubernetes.podspec-persistent-volume-claim: enabled
      kubernetes.podspec-persistent-volume-write: enabled
      kubernetes.podspec-schedulername: enabled
      kubernetes.podspec-securitycontext: enabled
      kubernetes.podspec-tolerations: enabled
      kubernetes.podspec-volumes-emptydir: enabled
      kubernetes.podspec-fieldref: enabled
      kubernetes.containerspec-addcapabilities: enabled
      kubernetes.podspec-nodeselector: enabled
      multi-container: enabled
    domain:
      svc.cluster.local: ""  # Use internal Kubernetes DNS
    network:
      domainTemplate: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
      ingress-class: kourier.ingress.networking.knative.dev
      default-external-scheme: http

  high-availability:
    replicas: 2

  ingress:
    kourier:
      enabled: true

