# KnativeServing Custom Resource for Air-Gapped Environments
# This file is auto-generated by install.sh - do not edit manually.

apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # Override container registry for air-gapped environment
  registry:
    # Image pull secrets for private registry authentication
    imagePullSecrets:
      - name: knative-registry-creds
    # Default uses ${NAME} placeholder for component name
    default: ${PRIVATE_REGISTRY_URL}/knative/${NAME}:v${KNATIVE_VERSION}
    override:
      # Queue proxy (injected into user workloads)
      queue-proxy: ${PRIVATE_REGISTRY_URL}/knative/queue:v${KNATIVE_VERSION}
      # Kourier ingress components (use container names as keys)
      net-kourier-controller/controller: ${PRIVATE_REGISTRY_URL}/knative/kourier:v${KNATIVE_VERSION}
      kourier-gateway: ${PRIVATE_REGISTRY_URL}/envoyproxy/envoy:${ENVOY_VERSION}
      # Post-install job images
      cleanup: ${PRIVATE_REGISTRY_URL}/knative/cleanup:v${KNATIVE_VERSION}
      migrate: ${PRIVATE_REGISTRY_URL}/knative/migrate:v${KNATIVE_VERSION}

  config:
    config-deployment:
      # Queue-proxy sidecar image for user workloads (critical for air-gapped)
      queue-sidecar-image: ${PRIVATE_REGISTRY_URL}/knative/queue:v${KNATIVE_VERSION}
    config-autoscaler:
      enable-scale-to-zero: "true"
    config-features:
      kubernetes.podspec-affinity: enabled
      kubernetes.podspec-init-containers: enabled
      kubernetes.podspec-persistent-volume-claim: enabled
      kubernetes.podspec-persistent-volume-write: enabled
      kubernetes.podspec-schedulername: enabled
      kubernetes.podspec-securitycontext: enabled
      kubernetes.podspec-tolerations: enabled
      kubernetes.podspec-volumes-emptydir: enabled
      kubernetes.podspec-fieldref: enabled
      kubernetes.containerspec-addcapabilities: enabled
      kubernetes.podspec-nodeselector: enabled
      multi-container: enabled
    domain:
      svc.cluster.local: ""  # Use internal Kubernetes DNS
    network:
      domainTemplate: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
      ingress-class: kourier.ingress.networking.knative.dev
      default-external-scheme: http

  high-availability:
    replicas: 2

  ingress:
    kourier:
      enabled: true
